<a href="https://colab.research.google.com/github/kusakina0608/ImageDataProcessing/blob/master/day2_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch를 이용한 머신러닝

Google의 Tensorflow
Facebook의 PyTorch

Why PyTorch?
 - Can check values while running
 - Easy deployment to C++
 - Performance
 - Researchers prefer PyTorch to Tensorflow



## PyTorch Fundamentals

Tensor
 - 텐서는 다차원 배열을 처리하기 위한 데이터 구조이다.
 - Numpy의 ndarray(n dimensional array)와 거의 같은 API를 지니고 있다.
 - GPU를 사용한 계산도 지원한다.
   (Numpy의 ndarray는 GPU를 사용하기가 어렵지만, Tensor는 GPU로 빠르게 처리가 가능하다.)
 - 텐서는 각 데이터형별로 정의돼 있다.
 - GPU상에서 계산할 때는 torch.cuda.FloatTensor 등을 사용한다.
 - Tensor는 FloatTensor의 별칭(alias)이다.
 - 어떤 형의 텐서이건 torch.tensor라는 함수로 작성할 수 있다.

## PyTorch의 기본

PyTorch는 원래 C++에 있던 Torch를 Python에서 쓸 수 있도록 한 것.

In [2]:
import torch
t = torch.tensor([[1., 2.], [3., 4.]])
print(t)

tensor([[1., 2.],
        [3., 4.]])




---


device="cuda:0"를 명시해 주어야만 텐서가 GPU에 할당된다.

In [3]:
t = torch.tensor([[1., 2.], [3., 4.]], device="cuda:0")
print(t)

tensor([[1., 2.],
        [3., 4.]], device='cuda:0')




---


torch.tensor의 기본 데이터 타입은 float32이다.<br>
dtype=torch.float64를 따로 명시해 주어야만 64bit float로 텐서가 생성된다.

In [4]:
t = torch.tensor([[1., 2.], [3., 4.]], dtype=torch.float64)
print(t)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)




---


0부터 9까지의 정수로 이루어진 1차원 Tensor

In [5]:
t = torch.arange(0, 10)
print(t)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])




---

모든 값이 0인 100x10의 Tensor를 GPU에서 생성
두 코드는 같은 동작을 한다.

In [0]:
t = torch.zeros(100, 10).to("cuda:0")
t = torch.zeros((100, 10), device="cuda:0")

print(t)



---


정규분포를 따르는 난수로 100x10의 Tensor를 생성

In [6]:
t = torch.randn(100, 10)
print(t)

tensor([[ 1.7140e-01, -1.0880e+00,  5.3741e-02, -1.6216e-01,  3.5411e-01,
          8.8906e-01, -1.9573e+00,  8.8121e-01,  3.5016e-01, -2.5917e-01],
        [-3.4835e-01,  2.1276e+00,  1.1517e+00,  1.2675e+00, -1.0220e+00,
          1.1052e+00,  2.0641e-01,  2.7981e+00, -1.1195e+00, -1.4853e-01],
        [-7.9030e-01,  6.0993e-01, -8.8410e-01,  3.8178e-01,  1.5034e+00,
         -1.3742e+00,  3.9295e-01,  6.0804e-01,  4.8383e-01, -6.6233e-01],
        [ 1.5993e+00, -2.1546e-01,  3.6316e-01,  4.9823e-01, -1.1279e+00,
         -1.5876e+00,  1.0657e+00,  6.3706e-01,  3.8041e-01,  1.3199e-01],
        [-1.0146e+00, -1.1015e+00,  1.3256e+00,  1.4621e+00, -1.7124e+00,
         -1.3427e+00,  1.9111e-01, -7.4934e-01,  3.3116e-01, -1.1926e+00],
        [-7.5445e-01, -4.3875e-01, -5.0018e-01, -1.5051e+00,  2.6851e-01,
          8.0480e-01, -1.1924e+00, -6.3061e-01,  6.9565e-01,  1.7205e-01],
        [ 1.2979e+00,  7.8025e-01,  6.9140e-01, -1.1858e+00, -1.4414e+00,
         -6.5024e-01, -1.2877e+0



---


Tensor의 shape는 size 메서드로 확인할 수 있다.

In [7]:
t.size()

torch.Size([100, 10])



---


!nvidia-smi 명령어로 GPU 정보를 확인할 수 있다.

In [8]:
!nvidia-smi

Tue Aug 27 00:40:01 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.40       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   73C    P0    72W / 149W |    337MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

## Torch tensor와 Numpy ndarray간의 변환

numpy 메서드를 사용해 ndarray로 변환

In [9]:
import torch
import numpy

t = torch.tensor([[1., 2.], [3., 4.]])
x = t.numpy()

print(x)

[[1. 2.]
 [3. 4.]]




---


GPU에 할당된 tensor를 numpy ndarray로 변환하기 위해서는 반드시 CPU로 옮긴 뒤 변환해야 한다.

In [10]:
t = torch.tensor([[1., 2.], [3., 4.]], device="cuda:0")
x = t.to("cpu").numpy()

print(x)

[[1. 2.]
 [3. 4.]]




---

CPU로 이동시키지 않고 GPU에 할당된 Tensor를 ndarray로 변환하려 할 경우 에러가 발생한다.

In [11]:
t = torch.tensor([[1., 2.], [3., 4.]], device="cuda:0")
x = t.numpy()

print(x)

TypeError: ignored

## Tensor의 인덱스 조작

스칼라 첨자 지정

In [12]:
t = torch.tensor([[1., 2., 3.], [4., 5., 6.]])
t[0, 2]

tensor(3.)



---


슬라이스로 지정

In [13]:
t[:, :2]

tensor([[1., 2.],
        [4., 5.]])



---


리스트로 지정

In [14]:
t[:, [1,2]]

tensor([[2., 3.],
        [5., 6.]])



---


마스크 배열을 사용해서 3보다 큰 부분만 선택

In [15]:
t[t > 3]

tensor([4., 5., 6.])

t[t > 3]은 아래와 같은 mask를 생성한다.<br>
[[F, F, F]<br>
 [T, T, T]]



---

특정 조건의 요소 선택 예시

In [18]:
t = torch.tensor([[1., 2., 3., 7., 8., 9.], [4., 5., 6., 1., 2., 3.]])
t[t > 3]

tensor([7., 8., 9., 4., 5., 6.])



---


[0, 1]의 요소를 100으로 설정

In [21]:
t = torch.tensor([[1., 2., 3.], [4., 5., 6.]])
t[0, 1] = 100
print(t)

tensor([[  1., 100.,   3.],
        [  4.,   5.,   6.]])




---


슬라이스를 사용한 일괄 대입

In [22]:
t[:, 1] = 200
print(t)

tensor([[  1., 200.,   3.],
        [  4., 200.,   6.]])




---


마스크 배열을 사용해서 특정 조건의 요소만 치환

In [23]:
t[t > 10] = 20
print(t)

tensor([[ 1., 20.,  3.],
        [ 4., 20.,  6.]])


## Tensor 연산

scalar: <br>
vector: 1차원<br>
matrix: 2차원<br>
tensor: 3차원

In [0]:
v = torch.tensor([1., 2., 3.])
w = torch.tensor([0., 10., 20.])
m = torch.tensor([[0., 1., 2.,], [100., 200., 300.]])



---


벡터와 스칼라의 덧셈

In [25]:
v2 = v + 10
print(v2)

tensor([11., 12., 13.])




---

벡터와 스칼라의 제곱

In [26]:
v2 = v ** 2
print(v2)

tensor([1., 4., 9.])




---


동일한 길이의 벡터 간 뺄셈

In [27]:
z = v - w
print(z)

tensor([  1.,  -8., -17.])




---


여러 가지 조합

In [28]:
u = 2 * v - w / 10 + 6.0
print(u)

tensor([ 8.,  9., 10.])




---

행렬과 스칼라의 곱

In [29]:
m2 = m * 2.0
print(m2)

tensor([[  0.,   2.,   4.],
        [200., 400., 600.]])




---


(2, 3)인 행렬과 (3,)인 벡터의 덧셈이므로 각 행에 적용된다.<br>
Ref. numpy's broadcasting

In [30]:
m3 = m + v
print(m3)

tensor([[  1.,   3.,   5.],
        [101., 202., 303.]])




---


행렬간 덧셈

In [31]:
m4 = m + m
print(m4)

tensor([[  0.,   2.,   4.],
        [200., 400., 600.]])




---

수학 함수를 포함하는 수식

In [0]:
X = torch.randn(100, 10)
y = X * 2 + torch.abs(X)



---

평균 구하기<br>(함수가 아닌 메서드를 사용해도 가능)

In [33]:
m = torch.mean(X)
print(m)

tensor(0.0224)


In [34]:
m = X.mean()
print(m)

tensor(0.0224)




---


0차원인 Tensor는 item 메서드로 값을 추출할 수 있다.

In [35]:
m_value = m.item()
print(m_value)

0.022426193580031395




---


차원을 지정하여 계산할 수 있다.<br>
다음은 '행'(row)단위로 평균값을 계산한 것이다.

In [36]:
m2 = X.mean(0)
print(m2)

tensor([-0.0054,  0.0116, -0.0053,  0.1063, -0.0216,  0.0106,  0.1164, -0.0534,
         0.0770, -0.0120])


## 행렬 Tensor의 인덱스 조작

In [0]:
x1 = torch.tensor([[1., 2.], [3., 4.]]) # 2x2 matrix
x2 = torch.tensor([[10., 20., 30.], [40., 50., 60.]]) # 2x3 matrix

2x2를 4x1로 보여준다.

In [39]:
x1.view(4, 1)

tensor([[1.],
        [2.],
        [3.],
        [4.]])



---


-1을 사용하면 표현할 수 있는 자동화된 값으로 대체<br>
(행, 열 둘 중에서 한 곳만 사용가능)

In [41]:
x1.view(1, -1)

tensor([[1., 2., 3., 4.]])



---

2x3을 전치해서 3x2로 만든다.<br>
t: transpose

In [42]:
x2.t()

tensor([[10., 40.],
        [20., 50.],
        [30., 60.]])



---

dim=1로 결합하면 열에 붙여서 2x5의 Tensor로 만든다.

In [43]:
torch.cat([x1,x2], dim=1)

tensor([[ 1.,  2., 10., 20., 30.],
        [ 3.,  4., 40., 50., 60.]])



---

transpose 메서드를 사용하여 데이터의 형식을 바꿀 수 있다.<br>
PyTorch의 딥러닝 모델에서는 chw형식의 텐서를 입력받기 때문에 차원 변환 과정이 필요하다.<br>
hwc: height, width, channel<br>
chw: channel, height, width<br>

In [44]:
hwc_img_data = torch.rand(100, 64, 32, 3)
chw_img_data = hwc_img_data.transpose(1,2).transpose(1,3)
print(hwc_img_data)
print(chw_img_data)

tensor([[[[4.8310e-01, 1.8907e-01, 9.7491e-01],
          [7.7309e-01, 5.6623e-01, 5.5000e-01],
          [3.3840e-01, 6.0811e-01, 1.5958e-01],
          ...,
          [8.3505e-01, 2.2634e-01, 5.9647e-01],
          [9.2603e-01, 1.7945e-01, 2.9459e-01],
          [1.6121e-02, 1.5264e-01, 9.2220e-01]],

         [[2.9703e-01, 2.0737e-01, 7.4805e-01],
          [3.7615e-01, 3.8823e-01, 5.6646e-01],
          [6.6303e-01, 5.0976e-01, 8.6219e-01],
          ...,
          [4.4727e-01, 8.0340e-02, 1.0786e-01],
          [9.5368e-01, 1.9651e-02, 1.8406e-01],
          [4.8587e-01, 9.3731e-01, 7.3123e-02]],

         [[7.1833e-01, 2.2011e-01, 1.9203e-01],
          [2.3344e-01, 5.9289e-01, 2.7478e-01],
          [4.1604e-01, 6.5615e-01, 8.2644e-01],
          ...,
          [3.7652e-01, 9.7769e-01, 9.7591e-01],
          [9.9805e-01, 6.0983e-01, 6.0042e-01],
          [7.2201e-01, 8.6606e-01, 4.7953e-01]],

         ...,

         [[5.8074e-01, 2.3482e-01, 9.4802e-01],
          [1.4415e-01,

In [45]:
print(hwc_img_data.size())
print(chw_img_data.size())

torch.Size([100, 64, 32, 3])
torch.Size([100, 3, 64, 32])




---

벡터의 내적

In [47]:
v = torch.arange(0, 10)
d = torch.dot(v, v)

print(v)
print(d)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor(285)




---

행렬과 벡터의 곱

In [48]:
m = torch.randn(100, 10)
v = torch.randn(10)

v2 = torch.mv(m, v)

print(v2)

tensor([-2.2881, -2.9710, -1.2327,  1.8682, -1.3685,  2.7584, -2.9563, -1.2882,
        -4.2611,  2.4036,  2.3437, -4.5590, -1.9394, -2.9344, -0.3133, -3.3062,
         3.4346, -0.7190,  2.8800, -3.1279, -6.8427,  4.2219, -0.1384,  1.0504,
         1.9127, -0.3627,  1.7589,  5.4850,  3.0982, -5.8452,  0.6526, -3.3100,
         0.8896, -0.8182, -1.5167,  3.9932, -5.4556,  0.7889,  2.6552, -1.4356,
        -3.3821,  2.4636,  3.4488,  2.3951, -1.4792, -4.0821, -1.5202, -3.2447,
         0.8412, -1.5344, -4.2193, -0.6448, -1.5578, -1.2811, -4.1185,  5.7790,
        -1.1200, -6.2114,  0.5258,  3.4505,  1.1027,  1.1140, -0.2495,  1.5143,
         5.8674,  0.5611, -2.5172, -1.9360, -3.1401,  2.2183,  4.0506, -2.4778,
        -3.6895,  6.4766,  4.4000,  1.1012,  0.0455,  1.3137, -0.2654, -1.0085,
         1.9715, -5.4614, -2.3489, -0.8017, -0.4813,  5.5252, -0.0700, -3.0704,
         1.8450, -1.5388,  1.1429,  1.3500,  1.7489, -0.5789, -1.5901, -1.5858,
         0.9813, -3.8224,  5.1666, -3.40



---

행렬과 행렬의 곱

In [49]:
m2 = torch.mm(m.t(), m)
print(m2)

tensor([[117.4180,  11.3457,  -8.3678, -13.9397,  -4.6812,  -6.5009,   7.3626,
           5.1230,  -2.2775, -12.4408],
        [ 11.3457,  81.3956,   5.5716,   0.5591, -17.0263,  -2.2422,  -4.5387,
          15.6283,   2.1009,   0.7688],
        [ -8.3678,   5.5716,  85.4389,  -7.8129,  -4.2595,  16.9217,  -8.5542,
         -11.1785,   9.3526,  12.1922],
        [-13.9397,   0.5591,  -7.8129, 117.8068,   6.1031,  -1.1097, -12.4753,
          -6.1865,   8.1462, -16.1614],
        [ -4.6812, -17.0263,  -4.2595,   6.1031, 118.8423,  13.5494, -10.2778,
          -3.1378,   1.6736,  14.5760],
        [ -6.5009,  -2.2422,  16.9217,  -1.1097,  13.5494, 103.4274, -19.3451,
           1.3264,   0.8972,   3.6372],
        [  7.3626,  -4.5387,  -8.5542, -12.4753, -10.2778, -19.3451, 100.4281,
           3.1255, -17.5335,  13.9677],
        [  5.1230,  15.6283, -11.1785,  -6.1865,  -3.1378,   1.3264,   3.1255,
         115.7418,   1.0392,  17.4748],
        [ -2.2775,   2.1009,   9.3526,   8.1462,



---

특이값 분해

In [50]:
u, s, v = torch.svd(m)

print('u =')
print(u)
print('s =')
print(s)
print('v =')
print(v)

u =
tensor([[ 5.0425e-02,  8.3112e-02,  5.1920e-02,  2.7887e-01, -7.4246e-02,
         -4.6333e-02, -2.1940e-02,  1.8953e-02, -3.1445e-02, -3.6664e-02],
        [-1.4018e-02,  4.4533e-02,  1.9445e-01, -5.9246e-02,  4.1065e-02,
         -1.2820e-01,  1.7865e-01, -3.2142e-02, -2.9913e-02, -1.1731e-01],
        [-3.9012e-02, -8.7564e-02, -9.6770e-02,  2.2864e-01, -9.5067e-02,
         -1.0910e-01, -1.1283e-01, -1.3499e-01,  1.9197e-02, -6.7153e-02],
        [ 6.1591e-02,  1.2367e-02, -9.6017e-02, -4.0513e-02, -7.0383e-02,
          1.6195e-01,  1.2369e-01, -3.3654e-02,  1.7444e-02,  2.2687e-01],
        [ 2.7227e-02, -9.3305e-02, -1.0433e-02,  6.4100e-02,  5.0859e-02,
          3.5362e-03, -4.8060e-02, -8.7408e-02,  2.3965e-02,  6.7527e-02],
        [-9.4532e-02, -1.0223e-01, -1.2814e-02, -1.4132e-01,  2.7700e-03,
         -7.8618e-02, -2.2169e-02, -1.7893e-01, -9.6760e-02,  8.1756e-02],
        [ 1.8845e-01,  2.9054e-02,  8.9387e-03,  4.3155e-03,  1.7168e-01,
         -1.7896e-01,  1.639

# 선형 회귀 모델
# (Linear Regression Model)

In [52]:
import torch
import matplotlib.pyplot as plt

basic = torch.ones(13, dtype=torch.float32)
x1_gas = torch.tensor([0, 73, 31, 39, 78, 22, 96, 82, 24, 81, 61, 28, 91], dtype=torch.float32)
x2_gas = torch.tensor([11, 88, 81, 2, 73, 88, 8, 64, 80, 45, 67, 34, 25], dtype=torch.float32)
toxic = torch.tensor([34, 411, 306, 85, 376, 309, 217, 357, 289, 298, 324, 159, 258])
print(toxic.dtype)

torch.int64


졸령

82.81